linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
  govet:
    check-shadowing: true
linters:
  enable-all: true
  fast: false
  disable:
    - depguard
    - nonamedreturns
    - paralleltest
    - interfacer
issues:
  max-same-issues: 0
  exclude-use-default: true
  exclude:
    - "Function 'SplitQuotes' has too many statements"
    - "cognitive complexity .* of func `SplitQuotes` is high"
    - "calculated cyclomatic complexity for function SplitQuotes is .*, max is"
    - "calculated cyclomatic complexity for function addToken is .*, max is"
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - dupword
        - funlen
        - lll
        - errcheck
